### ISSUE TITLE
Option to disable touchstart event for context menu item select

### ISSUE THREAD

**Issue by AgentSmith0** [lekoala/pure-context-menu#11]
On mobile devices the behavior is weird, if touchstart event is used to trigger item select, because the selection doesn't feel like a click.
Is it possible to add an option to disable the touchstart alias here: https://github.com/lekoala/pure-context-menu/blob/master/pure-context-menu.js#L102
Or maybe remove it completely?

**Comment by lekoala** [comment]
i made it configurable, maybe indeed it may lead to unexpected behavior
https://github.com/lekoala/pure-context-menu/commit/51aad0814f21019fc5aa2427fac2fad9bf46dee4
let me know what you think
