### ISSUE TITLE
Hide context menu when pressing right click second time

### ISSUE THREAD

**Issue by AgentSmith0** [lekoala/pure-context-menu#12]
Is there a way to toggle the context menu using right click, to hide the menu when already opened?

**Comment by lekoala** [comment]
i'm not sure what you mean. right click will open the same menu somewhere else
left click will close it
that's pretty much how it works everywhere :-)

**Comment by lekoala** [comment]
:-) why don't you give it a try? it should be a simple if a the start on the handle contextmenu that close it if the option is on

**Comment by lekoala** [comment]
like this
https://github.com/lekoala/pure-context-menu/releases/tag/1.2.5
:-)
should work fine from what i see
