### ISSUE TITLE
Feature idea: allow widths to be passed as options

### ISSUE THREAD

**Issue by teepeemm** [lekoala/pure-context-menu#16]
Would it make sense to add
```js
  minWidth: "120px",
  maxWidth: "240px",
```
to the `baseOptions`?  And then adjust `_buildContextMenu` to
```js
    contextMenu.style.minWidth = this._options.minWidth;
    contextMenu.style.maxWidth = this._options.maxWidth;
```

This would have the obvious benefit that if a context menu had unusually narrow or wide entries, we would be able to pass a few more options to the constructor.  My (very limited) testing shows that this works and doesn't break anything, but I'm not sure how extensive the testing would need to be in order to be sure.

**Comment by lekoala** [comment]
sounds like a great idea with no downside

https://github.com/lekoala/pure-context-menu/releases/tag/1.2.8

**Comment by teepeemm** [comment]
Thanks for implementing this so promptly.
