### ISSUE TITLE
Optional icons before items label

### ISSUE THREAD

**Issue by AgentSmith0** [lekoala/pure-context-menu#3]
Would be nice to have be able to choose icons that are placed before the items label. For reference: https://swisnl.github.io/jQuery-contextMenu/demo.html

**Comment by lekoala** [comment]
yes indeed ;-) i have no time to allocate for that but it should be fairly easy to do. i'm open to PR ;-)

**Comment by Frenzie** [comment]
What about changing this line to innerHTML? Although I suppose that might imply some added sanitation. My underlying thought is mainly that an icon in the sense of a PNG/SVG is a bit different than a `.fa` or a `.bi` class.

https://github.com/lekoala/pure-context-menu/blob/317b619943bb1fb28d7b7503d5e8b074e990d1db/pure-context-menu.js#L90

**Comment by lekoala** [comment]
@AgentSmith0 @Frenzie  you can check on master you can now do things like this

<img width="236" alt="image" src="https://github.com/lekoala/pure-context-menu/assets/250762/9ee3187b-e190-4a98-8f82-52dfab288fdc">

**Comment by Frenzie** [comment]
lgtm! :+1:

**Comment by lekoala** [comment]
maybe a blank icon, or some kind of dummy element ?
