### ISSUE TITLE
Changing context menu items based on target

### ISSUE THREAD

**Issue by AgentSmith0** [lekoala/pure-context-menu#5]
How is it possible to add/remove/disable items in the context menu dynamically after initialization, e.g. based on target?

**Comment by lekoala** [comment]
it's not currently possible, but since the menu is built from scratch each time, that should be really easy to do

see in _buildContextMenu . all it needs is some kind of hooks to adjust items before looping over them. you can make a PR if you feel comfortable :)

**Comment by lekoala** [comment]
@AgentSmith0 you can check on master actually you can simply use the show callback. i've passed the instance, you can call setItems and do whatever you like. i've added an example in the demo.html

**Comment by lekoala** [comment]
yep
https://github.com/lekoala/pure-context-menu/releases/tag/1.2.1
