### ISSUE TITLE
After opening context menu for body element, other dropdown menus somehow trigger old callback actions

### ISSUE THREAD

**Issue by AgentSmith0** [lekoala/pure-context-menu#7]
I recently noticed that other dropdown menu items with javascript onclick events trigger some old callback actions from an already closed context menu. Is there maybe some problem with finding the correct dropdown menu inside the DOM tree and assigning the correct event listeners?
I am currently trying to get a reduced example case.

**Comment by lekoala** [comment]
@AgentSmith0 i've changed how to handle the events so thats possible. an example would be great

**Comment by lekoala** [comment]
ok i see it seems it can get null target, it's fixed on master
